# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
import sys
from src.add_new_student import add_new_student
from src.take_attendance import take_attendance
import sqlite3


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1154, 872)
        MainWindow.setMinimumSize(QtCore.QSize(1154, 872))
        MainWindow.setMaximumSize(QtCore.QSize(1154, 872))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1161, 851))
        self.tabWidget.setMinimumSize(QtCore.QSize(1161, 851))
        self.tabWidget.setMaximumSize(QtCore.QSize(1161, 851))
        self.tabWidget.setStyleSheet("background-image: url(:/images/background.jpg);")
        self.tabWidget.setObjectName("tabWidget")
        self.student_tab = QtWidgets.QWidget()
        self.student_tab.setObjectName("tab")
        self.add_student_push_button = QtWidgets.QPushButton(self.student_tab)
        self.add_student_push_button.setGeometry(QtCore.QRect(593, 60, 131, 27))
        self.add_student_push_button.setStyleSheet("background: gray;")
        self.add_student_push_button.setObjectName("pushButton")
        self.student_table = QtWidgets.QTableWidget(self.student_tab)
        self.student_table.setGeometry(QtCore.QRect(130, 100, 901, 631))
        self.student_table.setStyleSheet("background: white;")
        self.student_table.setColumnCount(2)
        self.student_table.setObjectName("tableWidget")
        self.student_table.setColumnWidth(0, 450)
        self.student_table.setColumnWidth(1, 420)
        self.student_table.setHorizontalHeaderLabels(['FULL NAME', 'INDEX NUMBER'])
        self.name_text_input = QtWidgets.QLineEdit(self.student_tab)
        self.name_text_input.setGeometry(QtCore.QRect(130, 60, 191, 27))
        self.name_text_input.setStyleSheet("background: white;")
        self.name_text_input.setObjectName("lineEdit")
        self.index_number_text_input = QtWidgets.QLineEdit(self.student_tab)
        self.index_number_text_input.setGeometry(QtCore.QRect(362, 60, 171, 27))
        self.index_number_text_input.setStyleSheet("background: white;")
        self.index_number_text_input.setObjectName("lineEdit_2")
        self.load_student_data()
        self.add_student_push_button.clicked.connect(self.call_add_student)
        self.refresh_student_push_button = QtWidgets.QPushButton(self.student_tab)
        self.refresh_student_push_button.setGeometry(QtCore.QRect(540, 750, 94, 27))
        self.refresh_student_push_button.setStyleSheet("background: gray;")
        self.refresh_student_push_button.setObjectName("pushButton_2")
        self.refresh_student_push_button.clicked.connect(self.load_student_data)
        self.tabWidget.addTab(self.student_tab, "")
        self.attendance_tab = QtWidgets.QWidget()
        self.attendance_tab.setObjectName("tab_2")
        self.attendance_table = QtWidgets.QTableWidget(self.attendance_tab)
        self.attendance_table.setGeometry(QtCore.QRect(10, 90, 1131, 631))
        self.attendance_table.setStyleSheet("background: white;")
        self.attendance_table.setColumnCount(6)
        self.attendance_table.setObjectName("tableWidget_2")
        self.attendance_table.setColumnWidth(0, 200)
        self.attendance_table.setColumnWidth(1, 150)
        self.attendance_table.setColumnWidth(2, 250)
        self.attendance_table.setColumnWidth(3, 120)
        self.attendance_table.setColumnWidth(4, 185)
        self.attendance_table.setColumnWidth(5, 205)
        self.attendance_table.setHorizontalHeaderLabels(['FULL NAME', 'INDEX NUMBER', 'TIME REPORTED', 'PRESENT', 'COURSE CODE', 'DATE'])
        self.refresh_attendance_push_button = QtWidgets.QPushButton(self.attendance_tab)
        self.refresh_attendance_push_button.setGeometry(QtCore.QRect(520, 750, 94, 27))
        self.refresh_attendance_push_button.setStyleSheet("background: gray;")
        self.refresh_attendance_push_button.setObjectName("pushButton_3")
        self.refresh_attendance_push_button.clicked.connect(self.call_load_attendance)

        self.course_code_text_input = QtWidgets.QLineEdit(self.attendance_tab)
        self.course_code_text_input.setGeometry(QtCore.QRect(10, 50, 191, 27))
        self.course_code_text_input.setStyleSheet("background: white;")
        self.course_code_text_input.setObjectName("lineEdit_3")
        self.call_load_attendance()
        self.view_attendance_push_button = QtWidgets.QPushButton(self.attendance_tab)
        self.view_attendance_push_button.setGeometry(QtCore.QRect(240, 50, 141, 27))
        self.view_attendance_push_button.setStyleSheet("background: gray;")
        self.view_attendance_push_button.setObjectName("pushButton_4")
        self.view_attendance_push_button.clicked.connect(self.call_load_attendance)
        self.take_attendance_push_button = QtWidgets.QPushButton(self.attendance_tab)
        self.take_attendance_push_button.setGeometry(QtCore.QRect(430, 50, 141, 27))
        self.take_attendance_push_button.setStyleSheet("background: gray;")
        self.take_attendance_push_button.setObjectName("pushButton_5")
        self.take_attendance_push_button.clicked.connect(self.call_take_attendance)

        self.tabWidget.addTab(self.attendance_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    # Onclick action to call add_student function
    def call_add_student(self):
        if self.name_text_input.text() != '' and self.index_number_text_input.text() != '':
            return add_new_student(self.name_text_input.text(), self.index_number_text_input.text())
        return True


    # Onclick action to call load_attendacne function

    def call_load_attendance(self):
        if self.course_code_text_input.text() != '':
            return self.load_attendance(self.course_code_text_input.text())
        return True

    # Onclick action to call take_attendance function
    def call_take_attendance(self):
        if self.course_code_text_input.text() != '':
            return take_attendance(self.course_code_text_input.text())


    # This function fetch student and displays them in a table
    def load_student_data(self):
        # Connect to the attendance database
        con = sqlite3.connect('../attendance_db.sqlite')
        cur = con.cursor()
        # Select all student from the student table
        student_query = "select * from student;"
        # Set the number of rows in the attendance table to the number of results returned by the query
        table_row = 0
        self.student_table.setRowCount(len(cur.execute(student_query).fetchall()))
        # Iterate over each row returned by the query and add it to the table
        for row in cur.execute(student_query):
            # Convert the index number to a string
            index_number_str = str(row[2])
            # Add each item from the row to a specific column in the table
            self.student_table.setItem(table_row, 0, QtWidgets.QTableWidgetItem(row[1]))
            self.student_table.setItem(table_row, 1, QtWidgets.QTableWidgetItem(index_number_str))
            # Increment the row counter
            table_row += 1

    # This function loads attendance data for a specific course code and displays it in a table
    def load_attendance(self, course_code):
        # Connect to the attendance database
        con = sqlite3.connect('../attendance_db.sqlite')
        cur = con.cursor()
        # Select all data for the given course code
        query = "SELECT * FROM attendance where course_code = ?"
        # Set the number of rows in the attendance table to the number of results returned by the query
        tablerow = 0
        self.attendance_table.setRowCount(len(cur.execute(query, (course_code,)).fetchall()))
        # Iterate over each row returned by the query and add it to the table
        for row in cur.execute(query, (course_code,)):
            # Convert the index number to a string
            index_number_str = str(row[2])
            # Add each item from the row to a specific column in the table
            self.attendance_table.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(row[1]))
            self.attendance_table.setItem(tablerow, 1, QtWidgets.QTableWidgetItem(index_number_str))
            self.attendance_table.setItem(tablerow, 2, QtWidgets.QTableWidgetItem(row[3]))
            self.attendance_table.setItem(tablerow, 3, QtWidgets.QTableWidgetItem(row[4]))
            self.attendance_table.setItem(tablerow, 4, QtWidgets.QTableWidgetItem(row[5]))
            self.attendance_table.setItem(tablerow, 5, QtWidgets.QTableWidgetItem(row[6]))
            # Increment the row counter
            tablerow += 1


    def retranslateUi(self, MainWindow):
        # Create a translation object
        _translate = QtCore.QCoreApplication.translate
        # Set the window title
        MainWindow.setWindowTitle(_translate("MainWindow", "Facial Recognition Attendance System"))
        # Set the text of various buttons and input fields in the student tab
        self.add_student_push_button.setText(_translate("MainWindow", "Add student"))
        self.name_text_input.setPlaceholderText(_translate("MainWindow", "Enter  Fullname"))
        self.index_number_text_input.setPlaceholderText(_translate("MainWindow", "Enter  Index Number"))
        self.refresh_student_push_button.setText(_translate("MainWindow", "Refresh List"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.student_tab), _translate("MainWindow", "STUDENT"))
        # Set the text of various buttons and input fields in the attendance tab
        self.refresh_attendance_push_button.setText(_translate("MainWindow", "Refresh List"))
        self.course_code_text_input.setPlaceholderText(_translate("MainWindow", "Enter Course Code"))
        self.view_attendance_push_button.setText(_translate("MainWindow", "View Attendance"))
        self.take_attendance_push_button.setText(_translate("MainWindow", "Take Attendance"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.attendance_tab), _translate("MainWindow", "ATTENDANCE"))


if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        Form = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(Form)
        Form.show()
        sys.exit(app.exec_())